import type { SynthesizedReport } from '../types/review.js';
import type { MergedFinding, Severity } from '../types/finding.js';
import { scopeToString } from '../git/scope.js';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  error: '🟠',
  warning: '🟡',
  info: '🔵',
  style: '⚪',
};

const CONSENSUS_LABEL: Record<string, string> = {
  unanimous: '✅ Unanimous',
  majority: '🤝 Majority',
  split: '⚖️ Split',
};

function formatFinding(f: MergedFinding, index: number): string {
  const expertDots = f.contributingExperts.join(', ');
  let section = `### ${index + 1}. ${SEVERITY_EMOJI[f.severity]} \`${f.severity.toUpperCase()}\` ${f.title}

**File:** \`${f.file_path}:${f.line_start}-${f.line_end}\`
**Category:** ${f.category} | **Agreement:** ${Math.round(f.agreementScore * 100)}% (${CONSENSUS_LABEL[f.consensusStatus] ?? f.consensusStatus})
**Experts:** ${expertDots}

${f.description}`;

  if (f.suggested_fix) {
    section += `

**Suggested Fix:**
\`\`\`suggestion
${f.suggested_fix}
\`\`\``;
  }

  if (f.dissentingOpinions.length > 0) {
    section += `

**Dissenting Views:**`;
    for (const d of f.dissentingOpinions) {
      section += `\n> **${d.expertId}** (${d.severity}/${d.category}): ${d.reasoning.slice(0, 200)}${d.reasoning.length > 200 ? '...' : ''}`;
    }
  }

  return section;
}

export function formatMarkdown(report: SynthesizedReport): string {
  const scope = scopeToString(report.scope);
  const verdictBanner =
    report.summary.verdict === 'approve'
      ? '✅ **APPROVE**'
      : report.summary.verdict === 'request_changes'
        ? '🚫 **REQUEST CHANGES**'
        : '💬 **NEEDS DISCUSSION**';

  const bySev = report.summary.bySeverity;
  const severitySummary = Object.entries(bySev)
    .filter(([_, count]) => count > 0)
    .map(([sev, count]) => `${count} ${sev}`)
    .join(' · ');

  let md = `# CodeJury Review Report

| | |
|---|---|
| **Repo** | ${report.repo} |
| **Branch** | ${report.branch} |
| **Scope** | ${scope} |
| **Commit** | \`${report.commit.slice(0, 8)}\` |

## Verdict: ${verdictBanner}

${report.summary.narrative}

---

## Findings (${report.summary.totalFindings})

${severitySummary}

`;

  const grouped: Record<Severity, MergedFinding[]> = {
    critical: [],
    error: [],
    warning: [],
    info: [],
    style: [],
  };
  for (const f of report.findings) {
    grouped[f.severity].push(f);
  }

  let index = 0;
  for (const severity of ['critical', 'error', 'warning', 'info', 'style'] as Severity[]) {
    const findings = grouped[severity];
    if (findings.length === 0) continue;
    for (const f of findings) {
      md += formatFinding(f, index) + '\n\n---\n\n';
      index++;
    }
  }

  // Cost summary
  md += `## Cost Summary

| Expert | Cost |
|--------|------|
`;
  for (const meta of report.expertMetadata) {
    md += `| ${meta.expertId} (${meta.model}) | $${meta.costUsd.toFixed(4)} |\n`;
  }
  md += `| **Total** | **$${report.costBreakdown.totalCostUsd.toFixed(4)}** |\n`;

  md += `\n---\n\n_Generated by CodeJury v0.1.0 at ${report.timestamp.toISOString()}_\n`;

  return md;
}
